export const LOAD_PROFILES = 'LOAD_PROFILES';
export const SIM_REFRESHED = 'SIM_REFRESHED';
export const TOGGLE_PROFILE_START = 'TOGGLE_PROFILE_START';
export const DELETE_PROFILE_START = 'DELETE_PROFILE_START';
export const TOGGLE_EXTRA = 'TOGGLE_EXTRA';